#!/bin/sh

# Dependencies: equery (app-portage/gentoolkit)

# Add the following to the /etc/portage/bashrc (for emerge-hook)
# if [ "${EBUILD_PHASE}" == "postinst" ] || [ "${EBUILD_PHASE}" == "postrm" ]; then
#   /usr/bin/pkill -RTMIN+8 dwmblocks
# fi

case $BLOCK_BUTTON in
	#1) setsid -f "$TERMINAL" -e sb-popupgrade ;;
	#2) notify-send "$(/usr/bin/pacman -Qu)" ;;
	#3) notify-send "🎁 Upgrade module" "📦: number of upgradable packages
    #                                    - Left click to upgrade packages
    #                                    - Middle click to show upgradable packages" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo " $(equery list '*' | wc -l)"
