#!/bin/sh

# chao - CHoose Audio Output
# Dependencies: pulseaudio (pactl, pulsemixer), rdl (see other scripts)

# Get list of available (Analog) sinks
get_list() {
	pulsemixer --list-sinks | awk -F',' '{print $2}' | grep 'Analog Stereo' | awk -F': ' '{print $2}'
}

sink_id=$(pulsemixer --list-sinks | grep "$(get_list | rdl)" | awk -F',' '{print $1}' | sed 's/[^0-9]*//g')
echo $sink_id

pactl set-default-sink $sink_id
