#!/bin/sh

# rdl - Run Dmenu in List mode

# Gentoo colors
#normbgcolor="#1a1b25"
#normfgcolor="#bb9af7"
#selbgcolor="#a9b1d6"
#selfgcolor="#1a1b25"

# Void colors
normbgcolor="#000000"
normfgcolor="#d4d4d4"
selbgcolor="#57ff8f"
selfgcolor="#000000"

dmenu -l 20 -p "Choose an audio output:" -fn "monospace:size=11" -nb "$normbgcolor" -nf "$normfgcolor" -sb "$selbgcolor" -sf "$selfgcolor"
