#!/bin/bash

# if dwm exits 0, restart -- this allows hot reloading of config.h
while true; do
    # Log stderror to a file 
    #dwm 2> ~/.dwm.log
    # No error logging
    dwm >/dev/null 2>&1
done
